---
# Installs and configures the Rspamd spam filtering system.

- name: Ensure repository key for Rspamd is in place
  apt_key: url=http://rspamd.com/apt-stable/gpg.key state=present
  tags:
    - dependencies

- name: Add Rspamd repository
  apt_repository: repo="deb http://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main"
  tags:
    - dependencies

- name: Install Rspamd and Rmilter
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - rspamd
    - rmilter
  tags:
    - dependencies
