- name: Install Roundcube
  apt: pkg={{ item }} state=latest
  with_items:
    - roundcube
    - roundcube-plugins

- name: Configure the Apache HTTP server for roundcube
  template: src=etc_apache2_sites-available_roundcube.j2 dest=/etc/apache2/sites-available/roundcube group=www-data owner=www-data force=yes

- name: Configure roundcube
  copy: src=etc_roundcube_main.inc.php dest=/etc/roundcube/main.inc.php group=www-data owner=root mode=640 force=yes

- name: Configure roundcube's managesieve plugin
  copy: src=usr_share_roundcube_plugins_managesieve_config.inc.php dest=/usr/share/roundcube/plugins/managesieve/config.inc.php group=www-data owner=root mode=640 force=yes

- name: Enable roundcube site
  command: a2ensite roundcube creates=/etc/apache2/sites-enabled/roundcube
  notify: restart apache

